// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7rJwrPC9XwpMRQOSFojAu_dlLx8Isthk',
    appId: '1:564065476042:web:848f3574acba6625114333',
    messagingSenderId: '564065476042',
    projectId: 'collage-notice-board',
    authDomain: 'collage-notice-board.firebaseapp.com',
    storageBucket: 'collage-notice-board.appspot.com',
    measurementId: 'G-75P2X0TMH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ9DcTke4s5mjEo-VIZWdDsN1lC4x26EA',
    appId: '1:564065476042:android:8cfa8c5355a7e431114333',
    messagingSenderId: '564065476042',
    projectId: 'collage-notice-board',
    storageBucket: 'collage-notice-board.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC01VkWJsWMGhaRZwJOtLHzwQQ-Gg1MWBI',
    appId: '1:564065476042:ios:2de106ee301816a7114333',
    messagingSenderId: '564065476042',
    projectId: 'collage-notice-board',
    storageBucket: 'collage-notice-board.appspot.com',
    iosBundleId: 'com.example.collagenoticeboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC01VkWJsWMGhaRZwJOtLHzwQQ-Gg1MWBI',
    appId: '1:564065476042:ios:2de106ee301816a7114333',
    messagingSenderId: '564065476042',
    projectId: 'collage-notice-board',
    storageBucket: 'collage-notice-board.appspot.com',
    iosBundleId: 'com.example.collagenoticeboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7rJwrPC9XwpMRQOSFojAu_dlLx8Isthk',
    appId: '1:564065476042:web:8c57c576e6a0a822114333',
    messagingSenderId: '564065476042',
    projectId: 'collage-notice-board',
    authDomain: 'collage-notice-board.firebaseapp.com',
    storageBucket: 'collage-notice-board.appspot.com',
    measurementId: 'G-B5RHK3S91R',
  );

}